services:
    database:
        container_name: pahtoodb
        image: pahtoodb
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root@123
            MYSQL_DATABASE: pahtoo
            MYSQL_USER: pahtoo
            MYSQL_PASSWORD: pahtoo1888
        volumes:
            - pahtoo:/var/lib/mysql
volumes:
    pahtoo: